version: "3"

tasks:
  default:
    desc: Start services and show status.
    cmds:
      - task: start

  start:
    desc: Bring up infra and show status.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml up -d
      - docker compose -f deployment/docker-compose.local.yaml ps

  start:build:
    desc: Bring up infra (build images) and show status.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml up -d --build
      - docker compose -f deployment/docker-compose.local.yaml ps

  stop:
    desc: Stop services and keep volumes.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml down

  reset:
    desc: Stop services and remove volumes.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml down -v

  purge:
    desc: Purge all database data after confirmation.
    cmds:
      - |
          read -r -p "This will delete all MongoDB data. Type PURGE to continue: " confirm
          if [ "$confirm" = "PURGE" ]; then
            docker compose -f deployment/docker-compose.local.yaml down -v --remove-orphans
            docker volume rm -f mongodb_data "${PWD##*/}_mongodb_data" >/dev/null 2>&1 || true
          else
            echo "Purge cancelled."
          fi

  status:
    desc: Show service status.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml ps

  logs:
    desc: Tail Docker logs.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml logs -f

  mongo-ping:
    desc: Ping MongoDB from the container.
    cmds:
      - docker exec closer-mongodb mongosh --eval "db.adminCommand('ping')"

  dev:
    desc: Hot reload backend + frontend (Go via air, Vite HMR).
    cmds:
      - task: start
      - |
          sh -c '
          task dev:server &
          server_pid=$!
          task dev:web &
          web_pid=$!
          wait $server_pid $web_pid
          '

  dev:server:
    desc: Hot reload Go server.
    cmds:
      - task: goa:generate
      - sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go mod tidy'
      - sh -c 'cd server && go install github.com/air-verse/air@latest'
      - sh -c 'cd server && bin="$(go env GOBIN)"; if [ -z "$bin" ]; then bin="$(go env GOPATH)/bin"; fi; VITE_DEV_SERVER=http://localhost:5173 "$bin/air" -c .air.toml'

  dev:web:
    desc: Vite dev server (HMR).
    cmds:
      - sh -c 'cd web && npm install'
      - sh -c 'cd web && npm run dev'

  run:server:
    desc: Generate Goa artifacts, sync Go deps, and run the backend on localhost:3000.
    cmds:
      - task: goa:generate
      - sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go mod tidy'
      - sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go run ./cmd/server'

  goa:generate:
    desc: Generate Goa code and OpenAPI spec.
    cmds:
      - sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go generate ./design'

  goa:generate:all:
    desc: Regenerate Goa artifacts and verify Go build graph.
    cmds:
      - task: goa:generate
      - sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go test ./...'

  test:
    desc: Run backend unit tests.
    cmds:
      - sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go test $(go list ./... | grep -v "/gen")'

  cover:
    desc: Run backend tests with a 90% coverage gate.
    cmds:
      - |
          sh -c '
          set -eu
          cd server
          min=${COVER_MIN:-90.0}
          GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go test $(go list ./... | grep -v "/gen") -coverprofile=coverage.out
          total=$(GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go tool cover -func=coverage.out | awk "/^total:/ {gsub(/%/, \"\", \$3); print \$3}")
          echo "total coverage: ${total}%"
          awk -v total="$total" -v min="$min" "BEGIN { if ((total+0) < (min+0)) { printf(\"coverage gate failed (< %.1f%%)\\n\", min); exit 1 } }"
          '
