version: "3"

tasks:
  default:
    desc: Start services and show status.
    cmds:
      - task: start

  start:
    desc: Bring up the stack and show status.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml up -d
      - docker compose -f deployment/docker-compose.local.yaml ps

  up:
    desc: Start infra, build assets, and run the Go server.
    cmds:
      - "docker compose -f deployment/docker-compose.local.yaml up -d"
      - "sh -c 'cd web && npm install'"
      - "sh -c 'cd web && npm run build'"
      - "sh -c 'cd server && go mod tidy'"
      - "sh -c 'cd server && go run ./cmd/server'"

  docker:
    desc: Build and start the full Docker Compose stack.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml up -d --build
      - docker compose -f deployment/docker-compose.local.yaml ps

  stop:
    desc: Stop services and keep volumes.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml down

  reset:
    desc: Stop services and remove volumes.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml down -v

  purge:
    desc: Purge all database data after confirmation.
    cmds:
      - |
          read -r -p "This will delete all MongoDB data. Type PURGE to continue: " confirm
          if [ "$confirm" = "PURGE" ]; then
            docker compose -f deployment/docker-compose.local.yaml down -v --remove-orphans
            docker volume rm -f mongodb_data "${PWD##*/}_mongodb_data" >/dev/null 2>&1 || true
          else
            echo "Purge cancelled."
          fi

  status:
    desc: Show service status.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml ps

  logs:
    desc: Tail Docker logs.
    cmds:
      - docker compose -f deployment/docker-compose.local.yaml logs -f

  mongo-ping:
    desc: Ping MongoDB from the container.
    cmds:
      - docker exec closer-mongodb mongosh --eval "db.adminCommand('ping')"

  cerbos-health:
    desc: Check Cerbos health endpoint.
    cmds:
      - curl http://localhost:3592/_cerbos/health

  test:
    desc: Run backend unit tests.
    cmds:
      - "sh -c 'cd server && GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go test ./...'"

  cover:
    desc: Run backend tests with a 70% coverage gate.
    cmds:
      - |
          sh -c '
          cd server
          GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go test ./... -coverprofile=coverage.out
          total=$(GOCACHE=${GOCACHE:-/tmp/gocache-attesta} go tool cover -func=coverage.out | awk "/^total:/ {gsub(/%/, \"\", \$3); print \$3}")
          echo "total coverage: ${total}%"
          awk -v total="$total" "BEGIN { if ((total+0) < 70.0) { print \"coverage gate failed (< 70.0%)\"; exit 1 } }"
          '
