x-appwrite-base: &appwrite-base
  image: appwrite/appwrite:1.8.1
  environment: &appwrite-env
    _APP_ENV: production
    _APP_WORKER_PER_CORE: 6
    _APP_EDITION: self-hosted
    _APP_LOCALE: en
    _APP_CONSOLE_WHITELIST_ROOT: enabled
    _APP_SYSTEM_EMAIL_NAME: Appwrite
    _APP_SYSTEM_EMAIL_ADDRESS: attesta@apps.forkbomb.eu
    _APP_SYSTEM_TEAM_EMAIL: attesta@apps.forkbomb.eu
    _APP_SYSTEM_SECURITY_EMAIL_ADDRESS: certs@appwrite.io
    _APP_OPTIONS_ABUSE: enabled
    _APP_OPTIONS_ROUTER_PROTECTION: disabled
    _APP_OPTIONS_FORCE_HTTPS: disabled
    _APP_OPTIONS_ROUTER_FORCE_HTTPS: disabled
    _APP_DOMAIN: ${SERVICE_FQDN_APPWRITE}
    _APP_DOMAIN_TARGET_CNAME: localhost
    _APP_DOMAIN_TARGET_AAAA: ::1
    _APP_DOMAIN_TARGET_A: 127.0.0.1
    _APP_DOMAIN_TARGET_CAA: ""
    _APP_DNS: ""
    _APP_REDIS_HOST: ${SERVICE_NAME_APPWRITE_REDIS:-appwrite-redis}
    _APP_REDIS_PORT: 6379
    _APP_DB_HOST: ${SERVICE_NAME_APPWRITE_MARIADB:-appwrite-mariadb}
    _APP_DB_PORT: 3306
    _APP_DB_SCHEMA: appwrite
    _APP_USAGE_STATS: enabled
    _APP_STORAGE_DEVICE: local
    _APP_STORAGE_LIMIT: 30000000
    _APP_STORAGE_PREVIEW_LIMIT: 20000000
    _APP_MAINTENANCE_INTERVAL: 86400
    _APP_MAINTENANCE_RETENTION_EXECUTION: 1209600
    _APP_MAINTENANCE_RETENTION_CACHE: 2592000
    _APP_MAINTENANCE_RETENTION_ABUSE: 86400
    _APP_MAINTENANCE_RETENTION_AUDIT: 1209600
    _APP_MAINTENANCE_RETENTION_USAGE_HOURLY: 8640000
    _APP_MAINTENANCE_RETENTION_SCHEDULES: 86400
    _APP_GRAPHQL_MAX_BATCH_SIZE: 10
    _APP_GRAPHQL_MAX_COMPLEXITY: 250
    _APP_GRAPHQL_MAX_DEPTH: 3

x-appwrite-worker: &appwrite-worker
  <<: *appwrite-base
  depends_on:
    - appwrite-mariadb
    - appwrite-redis

services:
  appwrite:
    <<: *appwrite-base
    container_name: appwrite
    environment:
      <<: *appwrite-env
      SERVICE_URL_APPWRITE: /
      _APP_DB_USER: ${SERVICE_USER_MARIADB}
      _APP_DB_PASS: ${SERVICE_PASSWORD_MARIADB}
      _APP_OPENSSL_KEY_V1: ${SERVICE_PASSWORD_64_APPWRITE}
      _APP_SMTP_HOST: ${SERVICE_HOST_SMTP}
      _APP_SMTP_PORT: ${SERVICE_PORT_SMTP}
      _APP_SMTP_SECURE: ${SERVICE_SECURE_SMTP}
      _APP_SMTP_USERNAME: ${SERVICE_USERNAME_SMTP}
      _APP_SMTP_PASSWORD: ${SERVICE_PASSWORD_SMTP}
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-imports:/storage/imports:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - appwrite-mariadb
      - appwrite-redis
    healthcheck:
      test: ["CMD-SHELL", "curl -fsI http://localhost:80 | head -n 1 | grep -E '^HTTP/.* 3[0-9]{2} ' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-console:
    image: appwrite/console:7.5.7
    container_name: appwrite-console
    environment:
      SERVICE_URL_APPWRITE: /console
    healthcheck:
      test: ["CMD-SHELL", "curl -fsI http://localhost:80 | head -n 1 | grep -E '^HTTP/.* 3[0-9]{2} ' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-realtime:
    <<: *appwrite-base
    entrypoint: realtime
    container_name: appwrite-realtime
    environment:
      <<: *appwrite-env
      SERVICE_URL_APPWRITE: /v1/realtime
      _APP_DB_USER: ${SERVICE_USER_MARIADB}
      _APP_DB_PASS: ${SERVICE_PASSWORD_MARIADB}
      _APP_OPENSSL_KEY_V1: ${SERVICE_PASSWORD_64_APPWRITE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s localhost > /dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-worker-audits:
    <<: *appwrite-worker
    entrypoint: worker-audits
    container_name: appwrite-worker-audits
    environment:
      <<: *appwrite-env
      _APP_DB_USER: ${SERVICE_USER_MARIADB}
      _APP_DB_PASS: ${SERVICE_PASSWORD_MARIADB}
      _APP_OPENSSL_KEY_V1: ${SERVICE_PASSWORD_64_APPWRITE}
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[w]orker-audits' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-worker-webhooks:
    <<: *appwrite-worker
    entrypoint: worker-webhooks
    container_name: appwrite-worker-webhooks
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[w]orker-webhooks' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-worker-deletes:
    <<: *appwrite-worker
    entrypoint: worker-deletes
    container_name: appwrite-worker-deletes
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
      - appwrite-certificates:/storage/certificates:rw
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[w]orker-deletes' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-worker-databases:
    <<: *appwrite-worker
    entrypoint: worker-databases
    container_name: appwrite-worker-databases
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[w]orker-databases' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-worker-mails:
    <<: *appwrite-base
    entrypoint: worker-mails
    container_name: appwrite-worker-mails
    depends_on:
      - appwrite-redis
    environment:
      <<: *appwrite-env
      _APP_SMTP_HOST: ${SERVICE_HOST_SMTP}
      _APP_SMTP_PORT: ${SERVICE_PORT_SMTP}
      _APP_SMTP_SECURE: ${SERVICE_SECURE_SMTP}
      _APP_SMTP_USERNAME: ${SERVICE_USERNAME_SMTP}
      _APP_SMTP_PASSWORD: ${SERVICE_PASSWORD_SMTP}
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[w]orker-mails' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-worker-migrations:
    <<: *appwrite-base
    entrypoint: worker-migrations
    container_name: appwrite-worker-migrations
    volumes:
      - appwrite-imports:/storage/imports:rw
    depends_on:
      - appwrite-mariadb
    # disable healthcheck in coolify  
    exclude_from_hc: true

  appwrite-task-maintenance:
    <<: *appwrite-base
    entrypoint: maintenance
    container_name: appwrite-task-maintenance
    environment:
      <<: *appwrite-env
      _APP_DB_USER: ${SERVICE_USER_MARIADB}
      _APP_DB_PASS: ${SERVICE_PASSWORD_MARIADB}
      _APP_OPENSSL_KEY_V1: ${SERVICE_PASSWORD_64_APPWRITE}
    depends_on:
      - appwrite-redis
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[m]aintenance' || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  appwrite-mariadb:
    image: mariadb:10.11
    container_name: appwrite-mariadb
    networks:
      default:
        aliases:
          - appwrite-mariadb
          - mariadb
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
      - ./appwrite/appwrite-seed.sql:/seed/appwrite-seed.sql:ro
      - ./appwrite/mariadb-init-preview-seed.sh:/docker-entrypoint-initdb.d/10-preview-seed.sh:ro
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_MARIADBROOT
      - MYSQL_DATABASE=${_APP_DB_SCHEMA:-appwrite}
      - MYSQL_USER=$SERVICE_USER_MARIADB
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_MARIADB
      - MARIADB_AUTO_UPGRADE=1
      # Set this only in Coolify preview deployment env vars.
      - APPWRITE_RESTORE_SEED_SQL=${APPWRITE_RESTORE_SEED_SQL:-false}
    command: 'mysqld --innodb-flush-method=fsync'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 10s
      retries: 5

  appwrite-redis:
    image: redis:7.2.4-alpine
    container_name: appwrite-redis
    networks:
      default:
        aliases:
          - appwrite-redis
          - redis
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    volumes:
      - appwrite-redis:/data:rw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  cerbos:
    build:
      context: .
      dockerfile: deployment/Dockerfile.cerbos
    restart: unless-stopped
    command:
      - server
      - --config=/config/config.yaml

  attesta:
    build:
      context: .
      dockerfile: deployment/Dockerfile.coolify
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://${SERVICE_NAME_MONGODB:-mongodb}:27017
      CERBOS_URL: http://${SERVICE_NAME_CERBOS:-cerbos}:3592
      APPWRITE_ENDPOINT: http://${SERVICE_NAME_APPWRITE:-appwrite}:80/v1
      APPWRITE_PROJECT_ID:
      APPWRITE_API_KEY:
      APPWRITE_INVITE_REDIRECT_URL:
      APPWRITE_RESET_REDIRECT_URL:
      APPWRITE_ORG_ASSETS_BUCKET: org-assets
      SERVICE_FQDN_ATTESTA_3000:
    depends_on:
      - mongodb
      - cerbos
      - appwrite

  mongoexpress:
    image: mongo-express:1.0.2
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${SERVICE_NAME_MONGODB:-mongodb}:27017
      SERVICE_FQDN_MONGOEXPRESS_8081:
    depends_on:
      - mongodb

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-imports:
  appwrite-certificates:
  appwrite-config:
  appwrite-functions:
  appwrite-sites:
  appwrite-builds:
  mongodb_data:
