include:
  - path: ./appwrite/docker-compose.appwrite.yaml
    env_file:
      - ./appwrite/.env.appwrite.example

services:
  mongodb:
    image: mongo:7.0
    container_name: closer-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.50.0
    container_name: attesta-cerbos
    restart: unless-stopped
    command: ["server", "--config=/config/config.yaml"]
    ports:
      - "3592:3592"
    volumes:
      - ../cerbos/policies:/policies
      - ../cerbos/config:/config

  mongo-express:
    image: mongo-express:1.0.2
    container_name: closer-mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  mailpit:
    image: axllent/mailpit:v1.29.3
    container_name: attesta-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - default
      - appwrite

  attesta:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.local
    container_name: attesta
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      CERBOS_URL: http://cerbos:3592
      APPWRITE_ENDPOINT: http://appwrite/v1
      APPWRITE_PROJECT_ID: 69bbd0f4002a09b17d1e
      APPWRITE_API_KEY: standard_247a97933aa7a18373ffaad69c74b02dd5813b20d139f8f367a3ca443550d794c8438aeb4e1a7b79e299c83fe99aea52fcf4d29ad063659537e8f42d06dd69a5b59e5d50a16125c469a628aa0a3394c3cfaf32e5e4ca6e96c3ed855e3fe52bbe59b1ed44d3ae0a6fbb42746a5800d7588bcfeef93044ea2fa1efe1155a9b2024
      APPWRITE_INVITE_REDIRECT_URL: ${APPWRITE_INVITE_REDIRECT_URL:-http://localhost:3000/invite/accept}
      APPWRITE_RESET_REDIRECT_URL: ${APPWRITE_RESET_REDIRECT_URL:-http://localhost:3000/reset/confirm}
      APPWRITE_ORG_ASSETS_BUCKET: ${APPWRITE_ORG_ASSETS_BUCKET:-org-assets}
    ports:
      - "3030:3000"
    networks:
      - default
      - appwrite
    depends_on:
      - mongodb
      - cerbos
      - appwrite

volumes:
  mongodb_data:
    driver: local
